sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10.15.3"
before_install:
  - npm i -g npm
  - npm install -g grunt-cli
before_script:
  - npm prune
scripts:
  - npm run test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
