sudo: false
language: node_js
os:
  - windows
  - linux
  - osx
notifications:
  email: false
node_js:
  - "10.24.1"
cache:
  npm: true,
  directories:
    - "node_modules"
before_install:
  - npm install -g grunt-cli
scripts:
  - npm run test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
