sudo: false
language: node_js
notifications:
  email: false
node_js:
  - "10.15.3"
cache:
  npm: true,
  directories:
    - "node_modules"
before_install:
  - npm install -g grunt-cli
scripts:
  - npm run test
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
