sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10"
before_install:
  - npm i -g npm
  - npm install -g grunt-cli
scripts:
  - npm run test
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
